name: build & test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@master
        with:
          path: abscab/abscab-cpp
          
      - name: fake workspace
        run: cp abscab/abscab-cpp/.github/_WORKSPACE_TEMPLATE abscab/WORKSPACE
 
      - name: test abscab
        run: 
          pushd abscab && bazel test //abscab-cpp/abscab:TestAbscab --test_output=all ; popd
